routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('roue/for/check/php/version/detail',function(){
	ob_start();
    phpinfo();
    return ob_get_clean();
});





//Clear configurations:
			Route::get('/config-clear', function() {
				$status = Artisan::call('config:clear');
				return '<h1>Configurations cleared</h1>';
			});
			
			Route::get('/key-generaye', function() {
				$status = Artisan::call('key:generate');
				return '<h1>Configurations cleared</h1>';
			});

//Clear cache:
			Route::get('/cache-clear', function() {
				$status = Artisan::call('cache:clear');
				return '<h1>Cache cleared</h1>';
			});

//Clear configuration cache:
			Route::get('/config-cache', function() {
				$status = Artisan::call('config:cache');
				return '<h1>Configurations cache cleared</h1>';
			});



// Route::get('/', function () {
//     return view('welcome');
// });
//Admin Routes//

 Route::get('Admin','Admin\AdminController@view');
 Route::resource('Admin/construction','Admin\ConstructionController');
 Route::resource('Admin/Architecture','Admin\ArchitectureController');
 Route::resource('Admin/Interior','Admin\InteriorController');
 Route::resource('Admin/TownPlaning','Admin\TownPlanningController');
 Route::resource('Admin/Landscape','Admin\LandscapeController');
 Route::get('/Admin/company-register','Admin\AdminController@companyprofile');

 Route::resource('admin/company','Admin\CompanyController');
 Route::resource('admin/company-profile-contact','Admin\CompanyProfileContactController');
 Route::resource('admin/company-profile','Admin\CompanyProfileController');
 Route::resource('admin/company-profile-gallery','Admin\CompanyProfileGalleryController');
Route::resource('admin/setting','Admin\WebsiteSettingController');
Route::resource('admin/gallery','Admin\GalleryCategoryController');
Route::resource('admin/gallarysub','Admin\GallerysubController');
Route::resource('admin/gimages','Admin\GalleryimagesController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


// web controller 
Route::post('naqsha-search','Website\HomeController@naqsha_search')->name('naqsha-search');
Route::get('/','Website\HomeController@index')->name('home.index');

Route::get('about-us','Website\HomeController@about')->name('home.about');
Route::get('term-condition','Website\HomeController@term_condition')->name('home.term.condition');
Route::get('faq','Website\HomeController@faq')->name('home.faq');
Route::get('blogs','Website\HomeController@blogs')->name('home.blogs');

Route::get('architecture','Website\HomeController@architecture')->name('home.architecture');
Route::get('construction','Website\HomeController@construction')->name('home.construction');
Route::get('interior','Website\HomeController@interior')->name('home.interior');
Route::get('landscape','Website\HomeController@landscape')->name('home.landscape');
Route::get('town-planner','Website\HomeController@town_planner')->name('home.town.planner');
Route::get('engineers','Website\HomeController@engineers')->name('home.engineers');



Route::get("gallery3d-type/{id}","Website\HomeController@gallery_type")->name('gallery.3d.type');
Route::get("gallery-images/{id}","Website\HomeController@kanal_2_residential")->name('kanal.2.residential');
Route::get("d3_evlevation","Website\HomeController@d3_evlevation")->name('d3.evlevation');
Route::get("one_kanal_house","Website\HomeController@one_kanal_house")->name('one.kanal.house');

Route::get("interior_gallery_type","Website\HomeController@interior_gallery_type")->name('interior.gallery.type');
Route::get("commercial_interior","Website\HomeController@commercial_interior")->name('commercial.interior');
Route::get("residential_interior","Website\HomeController@residential_interior")->name('residential.interior');
Route::get("landscap_gallery","Website\HomeController@landscap_gallery")->name('landscap.gallery');
Route::get("landscapes","Website\HomeController@landscapes")->name('landscapes');

Route::get('company-detail/{id}','Website\HomeController@company_detail')->name('company.detail');

Route::post('sendEmail','Website\HomeController@sendEmail')->name('sendEmail');

Route::post('forBusinessEmail','Website\HomeController@forBusinessEmail')->name('forBusinessEmail');

resources/views/Admin/Sponser add/index.blade.php
@extends('Admin.admin-layout')

@push('css')
@endpush
@section('content')
<div class="container-fluid">
   <!-- BEGIN PAGE HEADER-->   
   <div class="row-fluid">
      <div class="span12">
         <!-- BEGIN THEME CUSTOMIZER-->
      
         <!-- END THEME CUSTOMIZER-->
         <!-- BEGIN PAGE TITLE & BREADCRUMB-->
         <h3 class="page-title">
            Architecture
         </h3>
        
         <!-- END PAGE TITLE & BREADCRUMB-->
      </div>
   </div>
   <!-- END PAGE HEADER-->
   <!-- BEGIN EDITABLE TABLE widget-->
   <div class="row-fluid">
      <div class="span12">
         <!-- BEGIN EXAMPLE TABLE widget-->
         <div class="widget purple">
            <div class="widget-title">
               <h4><i class="icon-reorder"></i> Architecture</h4>
               <span class="tools">
               <a href="javascript:;" class="icon-chevron-down"></a>
               <a href="javascript:;" class="icon-remove"></a>
               </span>
            </div>
            <div class="widget-body">
               <div>
                  <div class="clearfix">
                     <div class="btn-group">
                        <a href="{{ route('sponseradd.create') }}" id="editable-sample_new" class="btn green">
                        Add New <i class="icon-plus"></i>
                        </a>
                     </div>
                 
                  </div>
                  <div class="space15"></div>
                  <div id="editable-sample_wrapper" class="dataTables_wrapper form-inline" role="grid">
                     <div class="row-fluid">
                        <div class="span6">
                           <div id="editable-sample_length" class="dataTables_length">
                              <label>
                                 <select size="1" name="editable-sample_length" aria-controls="editable-sample" class="xsmall">
                                    <option value="5" selected="selected">5</option>
                                    <option value="15">15</option>
                                    <option value="20">20</option>
                                    <option value="-1">All</option>
                                 </select>
                                 records per page
                              </label>
                           </div>
                        <div class="span6">
                        </div>
                           <div class="dataTables_filter" id="editable-sample_filter"><label>Search: <input type="text" aria-controls="editable-sample" class="medium"></label></div>
                        </div>
                     </div>
                     <table class="table table-striped table-hover table-bordered dataTable" id="editable-sample" aria-describedby="editable-sample_info">
                        <thead>

                           <tr role="row">
                              <th>#</th>
                              <th class="sorting_disabled" role="columnheader" rowspan="1" colspan="1" aria-label="Username" style="width: 193px;">name</th>
                              <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Full Name: activate to sort column ascending" style="width: 288px;">gsc_id</th>
                              <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Full Name: activate to sort column ascending" style="width: 288px;">image_name</th>
                              
                              <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Edit: activate to sort column ascending" style="width: 89px;">Edit</th>
                              <th class="sorting" role="columnheader" tabindex="0" aria-controls="editable-sample" rowspan="1" colspan="1" aria-label="Delete: activate to sort column ascending" style="width: 129px;">Delete</th>
                           </tr>
                        </thead>
                        <tbody role="alert" aria-live="polite" aria-relevant="all">
                           @foreach($gc as $index => $value)
                        
                           <tr class="odd">
                              <td>{{ ++$index }}</td>
                              <td class="  sorting_1">{{ $value->name }}</td>
                              <td class="  sorting_1">{{ $value->image_name }}</td>
                              <td class="  sorting_1">{{ $value->gsc_id }}</td>
                              <td class=" ">
                                 <img width="100px" height="100px" style="border-radius: 100%;" src="{{ asset('images/settings'.'/'.$value->gc_image) }}">
                              </td>
                              
                              <td class=" "><a class="edit" href="{{ route('Architecture.edit',$value->id) }}">Edit</a></td>
                              <td class=" ">
                                 <a class="delete" href="javascript::void();" onclick="event.preventDefault();
                                                     document.getElementById('delete-arch-{{ $value->id }}').submit();">
                                                  Delete
                                 </a>
                                <form id="delete-arch-{{ $value->id }}" action="{{ route('Architecture.destroy',$value->id) }}" method="POST" style="display: none;">
                                 @method('delete')
                                        @csrf
                                </form>
                              </td>
                           </tr>
                           @endforeach
                        
                        </tbody>
                     </table>
                     <div class="row-fluid">
                        <div class="span6">
                           <div class="dataTables_info" id="editable-sample_info">Showing 1 to 5 of 12 entries</div>
                        </div>
                        <div class="span6">
                           <div class="dataTables_paginate paging_bootstrap pagination">
                              <ul>
                                 <li class="prev disabled"><a href="#">← Prev</a></li>
                                 <li class="active"><a href="#">1</a></li>
                                 <li><a href="#">2</a></li>
                                 <li><a href="#">3</a></li>
                                 <li class="next"><a href="#">Next → </a></li>
                              </ul>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <!-- END EXAMPLE TABLE widget-->
      </div>
   </div>
   <!-- END EDITABLE TABLE widget-->
</div>
@endsection

@push('js')

@endpush

resources/views/Admin/Sponser add/sponseradd.blade.php
@extends('Admin.admin-layout') @push('css') @endpush @section('content')

<div class="container-fluid">
    <!-- BEGIN PAGE HEADER-->

    <!-- BEGIN PAGE CONTENT-->
    <div class="row-fluid">
        <div class="span12">
            <!-- BEGIN VALIDATION STATES-->
            <div class="widget red">
                <div class="widget-title">
                    <h4><i class=" icon-key"></i>Construction</h4>
                    <span class="tools">
               <a href="javascript:;" class="icon-chevron-down"></a>
               <a href="javascript:;" class="icon-remove"></a>
               </span>
                </div>
                <div class="widget-body form">
                    <!-- BEGIN FORM-->
                    @if(isset($arch) && !empty($arch))
                    <form class="form-horizontal" method="post" action="{{ route('construction.update',$arch->id) }} " enctype="multipart/form-data">
                        @method('put') @else
                        <form class="form-horizontal" method="post" action="{{ route('sponseradd.store') }}" enctype="multipart/form-data">
                            @endif @csrf
                            


                                <div class="control-group error col-sm-12">
                                    <label class="control-label" for="inputError">Name</label>
                                    <div class="controls">
                                        <input type="text" name="name" id="name" class="form-control">
                                    </div>
                                </div>
                                   <div class="control-group error col-sm-12">
                                    <label class="control-label" for="inputError">image_name</label>
                                    <div class="controls">
                                        <input type="file" name="image_name" id="image_name" class="form-control">
                                    </div>
                                </div>
                             
                               
                               

                                <div class="form-actions">
                                    <button type="submit" class="btn btn-success">
                                        @if(isset($arch) && !empty($arch)) Update @else Save @endif
                                    </button>
                                    <button type="button" class="btn">Cancel</button>
                                </div>
                        </form>
                        <!-- END FORM-->
                        </div>
                </div>
                <!-- END VALIDATION STATES-->
            </div>
        </div>

@endsection 
@push('js') 

@endpush